import sys

path = '/Users/admin/Downloads/ai-sre-console_v2/src/App.tsx'
with open(path, 'r') as f:
    lines = f.readlines()

new_lines = []
skip = False
for line in lines:
    if "const InspectionTaskList" in line:
        new_lines.append("const InspectionTaskList: React.FC<{ onAction?: any, setShowBanner?: any, setSelectedTask?: any, analysisStatus?: any }> = ({ onAction, setShowBanner, setSelectedTask, analysisStatus }) => (\n")
        new_lines.append("  <div className=\"space-y-4\">\n")
        new_lines.append("    <div className=\"flex items-center justify-between mb-2\">\n")
        new_lines.append("      <div className=\"flex gap-2\">\n")
        new_lines.append("        {['全部', '异常/风险', '待处理', '已解决'].map((tag, i) => (\n")
        new_lines.append("          <button key={i} className={`px-3 py-1 rounded text-[10px] font-bold border transition-all ${i === 0 ? 'bg-blue-500/20 border-blue-500/40 text-blue-400' : 'bg-slate-800/40 border-slate-700/50 text-slate-500 hover:text-slate-300'}`}>\n")
        new_lines.append("            {tag}\n")
        new_lines.append("          </button>\n")
        new_lines.append("        ))}\n")
        new_lines.append("      </div>\n")
        new_lines.append("      <div className=\"flex items-center gap-3\">\n")
        new_lines.append("        <div className=\"relative group\">\n")
        new_lines.append("          <Search size={12} className=\"absolute left-2.5 top-1/2 -translate-y-1/2 text-slate-500\" />\n")
        new_lines.append("          <input type=\"text\" placeholder=\"搜索任务名称/摘要...\" className=\"bg-black/30 border border-slate-800 rounded-md pl-8 pr-3 py-1.5 text-[10px] text-slate-300 focus:outline-none focus:border-blue-500/50 w-64 transition-all\" />\n")
        new_lines.append("        </div>\n")
        new_lines.append("      </div>\n")
        new_lines.append("    </div>\n")
        new_lines.append("\n")
        new_lines.append("    <div className=\"space-y-4\">\n")
        new_lines.append("      {[\n")
        new_lines.append("        { \n")
        new_lines.append("          name: '核心支付链路稳定性巡检', \n")
        new_lines.append("          target: '集群 (K8s-Prod-Main)', \n")
        new_lines.append("          status: '高风险', \n")
        new_lines.append("          riskLevel: '高', \n")
        new_lines.append("          summary: '检测到支付网关 (payment-gw) 近 5 分钟 5xx 错误率突增至 15%，疑似三方依赖超时。',\n")
        new_lines.append("          updatedAt: '2024-04-12 14:05:12'\n")
        new_lines.append("        },\n")
        new_lines.append("        { \n")
        new_lines.append("          name: '数据库慢查询扫描', \n")
        new_lines.append("          target: '实例 (MySQL-Order-Primary)', \n")
        new_lines.append("          status: '异常', \n")
        new_lines.append("          riskLevel: '中', \n")
        new_lines.append("          summary: '存在 12 条执行超过 3s 的慢 SQL，主要集中在 order_info 表的全表扫描。',\n")
        new_lines.append("          updatedAt: '2024-04-12 13:50:45'\n")
        new_lines.append("        },\n")
        new_lines.append("        { \n")
        new_lines.append("          name: '全站 SSL 证书有效性监控', \n")
        new_lines.append("          target: '主机 (Slb-External-Node)', \n")
        new_lines.append("          status: '待查看', \n")
        new_lines.append("          riskLevel: '低', \n")
        new_lines.append("          summary: '有 2 个域名的证书即将于 15 天后到期，请及时更新。',\n")
        new_lines.append("          updatedAt: '2024-04-12 10:20:00'\n")
        new_lines.append("        },\n")
        new_lines.append("        { \n")
        new_lines.append("          name: '基础架构存储空间巡检', \n")
        new_lines.append("          target: '集群 (Ceph-Storage-01)', \n")
        new_lines.append("          status: '正常', \n")
        new_lines.append("          riskLevel: '低', \n")
        new_lines.append("          summary: '存储系统各分区使用率均在 60% 以下，IOPS 及延时指标正常。',\n")
        new_lines.append("          updatedAt: '2024-04-12 09:15:33'\n")
        new_lines.append("        }\n")
        new_lines.append("      ].map((task, idx) => (\n")
        new_lines.append("        <div \n")
        new_lines.append("          key={idx} \n")
        new_lines.append("          onClick={() => { setSelectedTask(task); setShowBanner(true); }}\n")
        new_lines.append("          className=\"bg-[#141418] border border-slate-800 rounded-xl p-5 hover:border-blue-500/50 hover:bg-blue-600/[0.02] transition-all group cursor-pointer relative\"\n")
        new_lines.append("        >\n")
        new_lines.append("          <div className=\"mb-5\">\n")
        new_lines.append("            <div className=\"flex items-center gap-3 mb-2.5\">\n")
        new_lines.append("               <div className={`w-1.5 h-1.5 rounded-full ${task.status === '正常' ? 'bg-emerald-500 shadow-[0_0_8px_rgba(16,185,129,0.5)]' : task.status === '高风险' ? 'bg-rose-500 animate-pulse shadow-[0_0_8px_rgba(244,63,94,0.5)]' : 'bg-orange-500 shadow-[0_0_8px_rgba(249,115,22,0.5)]'}`} />\n")
        new_lines.append("               <h4 className=\"text-sm font-bold text-slate-100 group-hover:text-blue-400 transition-colors uppercase tracking-tight font-mono\">{task.name}</h4>\n")
        new_lines.append("               <span className={`px-2 py-0.5 rounded text-[9px] font-black uppercase text-white ${task.riskLevel === '高' ? 'bg-rose-600' : task.riskLevel === '中' ? 'bg-orange-600' : 'bg-blue-600'}`}>\n")
        new_lines.append("                 风险:{task.riskLevel}\n")
        new_lines.append("               </span>\n")
        new_lines.append("            </div>\n")
        new_lines.append("            <p className=\"text-[11px] text-slate-500 leading-relaxed font-bold italic ml-4.5 border-l border-slate-800 pl-3\">\n")
        new_lines.append("               {task.summary}\n")
        new_lines.append("            </p>\n")
        new_lines.append("          </div>\n")
        new_lines.append("\n")
        new_lines.append("          <div className=\"grid grid-cols-2 gap-y-3 gap-x-8 mb-5 py-3 border-y border-slate-800/50 pointer-events-none\">\n")
        new_lines.append("             <div className=\"flex items-center gap-4\">\n")
        new_lines.append("                <span className=\"text-[10px] text-slate-500 font-bold uppercase w-16\">巡检对象</span>\n")
        new_lines.append("                <span className=\"text-[11px] text-slate-300 font-medium\">{task.target}</span>\n")
        new_lines.append("             </div>\n")
        new_lines.append("             <div className=\"flex items-center gap-4\">\n")
        new_lines.append("                <span className=\"text-[10px] text-slate-500 font-bold uppercase w-16\">当前状态</span>\n")
        new_lines.append("                <span className={`text-[11px] font-black ${task.status === '正常' ? 'text-emerald-500' : task.status === '高风险' ? 'text-rose-500' : 'text-orange-500'}`}>{task.status}</span>\n")
        new_lines.append("             </div>\n")
        new_lines.append("             <div className=\"flex items-center gap-4\">\n")
        new_lines.append("                <span className=\"text-[10px] text-slate-500 font-bold uppercase w-16\">最近更新</span>\n")
        new_lines.append("                <span className=\"text-[11px] text-slate-400 font-mono tracking-tight\">{task.updatedAt}</span>\n")
        new_lines.append("             </div>\n")
        new_lines.append("          </div>\n")
        new_lines.append("\n")
        new_lines.append("          <div className=\"flex justify-end items-center gap-3\">\n")
        new_lines.append("            {analysisStatus?.[task.name] === 'completed' && (\n")
        new_lines.append("              <button \n")
        new_lines.append("                onClick={(e) => { e.stopPropagation(); onAction?.('VIEW_REPORT', { format: '0412_phased', ...task }); }}\n")
        new_lines.append("                className=\"flex items-center gap-2 px-4 py-2 rounded-lg border border-slate-700 hover:border-blue-500/50 text-slate-400 hover:text-blue-400 text-[11px] font-bold transition-all active:scale-95\"\n")
        new_lines.append("              >\n")
        new_lines.append("                <FileText size={14} /> 查看分析报告\n")
        new_lines.append("              </button>\n")
        new_lines.append("            )}\n")
        new_lines.append("            <button \n")
        new_lines.append("              onClick={(e) => { e.stopPropagation(); onAction?.('START_INSPECTION_ANALYSIS', { task }); }}\n")
        new_lines.append("              disabled={analysisStatus?.[task.name] === 'analyzing'}\n")
        new_lines.append("              className=\"flex items-center gap-2 px-6 py-2 rounded-lg bg-blue-600 text-white text-[11px] font-black hover:bg-blue-500 transition-all shadow-lg shadow-blue-500/20 active:scale-95 group-hover:scale-105 disabled:opacity-50\"\n")
        new_lines.append("            >\n")
        new_lines.append("              {analysisStatus?.[task.name] === 'analyzing' ? <RefreshCw size={14} className=\"animate-spin\" /> : <Bot size={12} />}\n")
        new_lines.append("              {analysisStatus?.[task.name] === 'analyzing' ? '分析中...' : '开始分析'}\n")
        new_lines.append("            </button>\n")
        new_lines.append("          </div>\n")
        new_lines.append("        </div>\n")
        new_lines.append("      ))}\n")
        new_lines.append("    </div>\n")
        new_lines.append("\n")
        new_lines.append("    <div className=\"flex items-center justify-between pt-6 border-t border-slate-800/80 text-[10px] text-slate-500\">\n")
        new_lines.append("      <div className=\"flex items-center gap-4\">\n")
        new_lines.append("         <span className=\"font-bold\">第 1-4 条，共 24 条</span>\n")
        new_lines.append("         <div className=\"flex items-center gap-1.5\">\n")
        new_lines.append("            <span className=\"opacity-50\">每页显示:</span>\n")
        new_lines.append("            <select className=\"bg-transparent border-none focus:ring-0 cursor-pointer font-bold text-slate-300\">\n")
        new_lines.append("               <option>10</option>\n")
        new_lines.append("               <option>20</option>\n")
        new_lines.append("               <option>50</option>\n")
        new_lines.append("            </select>\n")
        new_lines.append("         </div>\n")
        new_lines.append("      </div>\n")
        new_lines.append("      <div className=\"flex gap-2\">\n")
        new_lines.append("        <button className=\"px-3 py-1.5 bg-slate-800/80 rounded-lg border border-slate-700/50 hover:bg-slate-700 hover:text-white transition-all disabled:opacity-30 disabled:cursor-not-allowed font-bold\" disabled>PREV</button>\n")
        new_lines.append("        <button className=\"px-3.5 py-1.5 bg-blue-600 rounded-lg text-white font-black shadow-lg shadow-blue-500/20\">1</button>\n")
        new_lines.append("        <button className=\"px-3.5 py-1.5 bg-slate-800/80 rounded-lg border border-slate-700/50 hover:bg-slate-700 hover:text-white transition-all font-bold\">2</button>\n")
        new_lines.append("        <button className=\"px-3 py-1.5 bg-slate-800/80 rounded-lg border border-slate-700/50 hover:bg-slate-700 hover:text-white transition-all font-bold\">NEXT</button>\n")
        new_lines.append("      </div>\n")
        new_lines.append("    </div>\n")
        new_lines.append("  </div>\n")
        new_lines.append(");\n")
        skip = True
    elif "const InspectionDetailReport =" in line:
        skip = False
        new_lines.append(line)
    elif not skip:
        new_lines.append(line)

with open(path, 'w') as f:
    f.writelines(new_lines)
print("InspectionTaskList perfectly rebuilt.")
